version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - app-network

  books-service:
    build: ./books
    restart: always
    container_name: books-service
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    ports:
      - "5001:5001"
    expose:
      - 5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
