# # Use an official Python runtime as the base image
# FROM python:3.9

# # Set PYTHONUNBUFFERED environment variable
# ENV PYTHONUNBUFFERED=1

# # Set the working directory in the container
# WORKDIR /Books

# # Install the Python dependencies
# RUN pip install --no-cache-dir flask flask_restful requests pymongo

# # Copy the application files to the working directory
# COPY . .

# EXPOSE 5001

# # Run the Flask application
# CMD ["python", "booksmain.py"]
